<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_short_desc</name>
   <tag></tag>
   <elementGuidId>5268873e-6cd9-4743-ac04-d24faade5c1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='shortDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#shortDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Mô tả ngắn về sản phẩm (hiển thị ở trang danh sách sản phẩm)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>318d52ae-03c0-4101-96f2-e1e6fda9f661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1c1b3d74-14ad-4a88-b77d-85e358a3546c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shortDescription</value>
      <webElementGuid>d88aaacc-e3d1-4c49-9530-7362721fb879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shortDescription</value>
      <webElementGuid>b8f19c53-fff7-4150-9efd-399dc7f89317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>bedc682a-23af-4fc7-ba6b-642c98b9d989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mô tả ngắn về sản phẩm (hiển thị ở trang danh sách sản phẩm)</value>
      <webElementGuid>a2582da0-ca1d-4747-b6ec-55640691009b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shortDescription&quot;)</value>
      <webElementGuid>b065de0a-7dfd-49ea-8ce7-bee24731afbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='shortDescription']</value>
      <webElementGuid>643253a0-5691-416a-98a3-7cc19a324ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div[3]/div[2]/div/div/div/div/div/form/div[9]/div/textarea</value>
      <webElementGuid>ae642688-defa-4ff8-bba6-fed773188d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>06e34b80-10fd-4f83-b32c-47732422286f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'shortDescription' and @name = 'shortDescription' and @placeholder = 'Mô tả ngắn về sản phẩm (hiển thị ở trang danh sách sản phẩm)']</value>
      <webElementGuid>84633f2e-5779-43d0-a20b-7d6db6af257a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
