<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_notification_voucher_content</name>
   <tag></tag>
   <elementGuidId>4ee12476-9a31-40dd-b3b3-3d2264bfcdd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='coupon-message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#coupon-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Mã giảm giá không hợp lệ&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5f8015b2-f299-41de-b48e-cbf9e5c5a12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coupon-message</value>
      <webElementGuid>343d4838-7f36-4ec7-b124-d185f6fe41c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-text text-danger mt-2</value>
      <webElementGuid>cb706169-4dc4-4739-a2b5-98f46c6f1056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mã giảm giá không hợp lệ</value>
      <webElementGuid>3840eca6-2fb4-4e0e-8baa-92efb808bae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coupon-message&quot;)</value>
      <webElementGuid>f0741ca2-63ff-4623-b6b4-bbf57fe3955e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='coupon-message']</value>
      <webElementGuid>6b2d7c03-b7a0-4d7c-b985-912e50e37639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='coupon-form']/div[2]</value>
      <webElementGuid>a962cacd-9cc8-4a7d-8ec2-3fd6378a583e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Áp dụng'])[1]/following::div[1]</value>
      <webElementGuid>510de510-d733-4426-b2a0-f70696fdcd96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng cộng'])[1]/following::div[3]</value>
      <webElementGuid>7a1fe916-8768-4932-b4cb-2fd8861b51ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiến hành thanh toán'])[1]/preceding::div[1]</value>
      <webElementGuid>ac2e5fae-bee7-4999-8489-ffd2bdcd929d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mã giảm giá không hợp lệ']/parent::*</value>
      <webElementGuid>a2997743-56cc-42b0-92b1-6aace6ab221c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]</value>
      <webElementGuid>ab02179a-fc81-41f5-88d9-f4bd6bac1ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'coupon-message' and (text() = 'Mã giảm giá không hợp lệ' or . = 'Mã giảm giá không hợp lệ')]</value>
      <webElementGuid>db901235-aaae-46b4-a2f9-d7cf22c8b99d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
