<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Chn PhngX --X H MX Hng HX Lin HX _9e55bc</name>
   <tag></tag>
   <elementGuidId>7e3129c2-9386-42b1-a0ac-80c32d071988</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='phuong']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phuong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#phuong</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>521039c9-f186-4db5-a7bb-bf922f88273a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>66bb10a2-3112-443f-9586-fa98a89e8616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phuong</value>
      <webElementGuid>0906b96b-fc67-42fb-a35f-b58c800bd96f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ward</value>
      <webElementGuid>d8a44aa3-548f-449d-a715-da894d0a6622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Chọn Phường/Xã --Xã Hạ MỗXã Hồng HàXã Liên HàXã Liên HồngXã Liên TrungThị trấn PhùngXã Phương ĐìnhXã Song PhượngXã Tân HộiXã Tân LậpXã Thọ AnXã Thọ XuânXã Thượng MỗXã Trung ChâuXã Đan PhượngXã Đồng Tháp</value>
      <webElementGuid>2dcb3c15-72de-42db-8294-0a0adc78b03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phuong&quot;)</value>
      <webElementGuid>315daea1-8e5b-4df2-8f52-85a1d9fb5f08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='phuong']</value>
      <webElementGuid>d1139f17-1193-4626-8bd7-71c2cd2b9dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div[4]/div[3]/div/select</value>
      <webElementGuid>85859aa3-c27f-4681-98d8-bc3a87c77207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ĐĂNG KÝ'])[1]/following::select[3]</value>
      <webElementGuid>be4378e0-fd53-4e1d-9976-b27de016b7fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mật khẩu xác nhận không khớp'])[1]/preceding::select[1]</value>
      <webElementGuid>36e869e1-34c8-4b79-b20b-b8ee4c3b40c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng ký'])[1]/preceding::select[1]</value>
      <webElementGuid>a57d2ae3-b38f-4c9b-8ebd-b339b7fdab96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>afc89813-a047-4c33-9b81-50ecd57e20a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'phuong' and @name = 'ward' and (text() = '-- Chọn Phường/Xã --Xã Hạ MỗXã Hồng HàXã Liên HàXã Liên HồngXã Liên TrungThị trấn PhùngXã Phương ĐìnhXã Song PhượngXã Tân HộiXã Tân LậpXã Thọ AnXã Thọ XuânXã Thượng MỗXã Trung ChâuXã Đan PhượngXã Đồng Tháp' or . = '-- Chọn Phường/Xã --Xã Hạ MỗXã Hồng HàXã Liên HàXã Liên HồngXã Liên TrungThị trấn PhùngXã Phương ĐìnhXã Song PhượngXã Tân HộiXã Tân LậpXã Thọ AnXã Thọ XuânXã Thượng MỗXã Trung ChâuXã Đan PhượngXã Đồng Tháp')]</value>
      <webElementGuid>2111bc57-9bd9-4348-9c61-aee5b5e8adfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
