<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Chn QunHuyn --Huyn Ba VQun Ba nhQ_e2d5aa</name>
   <tag></tag>
   <elementGuidId>96439509-6de9-4314-b8a9-0624f6d01f25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='quan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#quan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#quan</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>85bfc655-7f4a-4242-a0b5-5e06872c4744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ea5805f8-0c28-42c6-99eb-6f3d5d9acb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quan</value>
      <webElementGuid>5c72a833-dc0d-44c9-aaf7-947f4530969a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>district</value>
      <webElementGuid>3d3f5305-eda8-4d3b-899b-d529cbaec59e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Chọn Quận/Huyện --Huyện Ba VìQuận Ba ĐìnhQuận Bắc Từ LiêmQuận Cầu GiấyHuyện Chương MỹHuyện Gia LâmQuận Hà ĐôngQuận Hai Bà TrưngHuyện Hoài ĐứcQuận Hoàn KiếmQuận Hoàng MaiQuận Long BiênHuyện Mê LinhHuyện Mỹ ĐứcQuận Nam Từ LiêmHuyện Phú XuyênHuyện Phúc ThọHuyện Quốc OaiHuyện Sóc SơnThị xã Sơn TâyQuận Tây HồHuyện Thạch ThấtHuyện Thanh OaiHuyện Thanh TrìQuận Thanh XuânHuyện Thường TínHuyện Ứng HòaHuyện Đan PhượngHuyện Đông AnhQuận Đống Đa</value>
      <webElementGuid>92974dca-2d9b-4537-85e4-1ebcfc4c627d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quan&quot;)</value>
      <webElementGuid>e6a90d71-e529-4be9-bd08-3fad37ef0f7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='quan']</value>
      <webElementGuid>cf5a85ed-5f96-43c8-a472-9aa678921924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div[4]/div[2]/div/select</value>
      <webElementGuid>7940b0b0-b4dc-4fab-8998-79acc6ce4d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ĐĂNG KÝ'])[1]/following::select[2]</value>
      <webElementGuid>36bd0d62-fea8-4555-b9dd-9c208b53155b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mật khẩu xác nhận không khớp'])[1]/preceding::select[2]</value>
      <webElementGuid>7e1caa71-2c4c-4356-a332-521761092430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng ký'])[1]/preceding::select[2]</value>
      <webElementGuid>9566cb6c-578e-41e3-a6db-5441b3bb9200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>9fd41dd3-954a-4113-9ddf-2818f7fe5fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'quan' and @name = 'district' and (text() = '-- Chọn Quận/Huyện --Huyện Ba VìQuận Ba ĐìnhQuận Bắc Từ LiêmQuận Cầu GiấyHuyện Chương MỹHuyện Gia LâmQuận Hà ĐôngQuận Hai Bà TrưngHuyện Hoài ĐứcQuận Hoàn KiếmQuận Hoàng MaiQuận Long BiênHuyện Mê LinhHuyện Mỹ ĐứcQuận Nam Từ LiêmHuyện Phú XuyênHuyện Phúc ThọHuyện Quốc OaiHuyện Sóc SơnThị xã Sơn TâyQuận Tây HồHuyện Thạch ThấtHuyện Thanh OaiHuyện Thanh TrìQuận Thanh XuânHuyện Thường TínHuyện Ứng HòaHuyện Đan PhượngHuyện Đông AnhQuận Đống Đa' or . = '-- Chọn Quận/Huyện --Huyện Ba VìQuận Ba ĐìnhQuận Bắc Từ LiêmQuận Cầu GiấyHuyện Chương MỹHuyện Gia LâmQuận Hà ĐôngQuận Hai Bà TrưngHuyện Hoài ĐứcQuận Hoàn KiếmQuận Hoàng MaiQuận Long BiênHuyện Mê LinhHuyện Mỹ ĐứcQuận Nam Từ LiêmHuyện Phú XuyênHuyện Phúc ThọHuyện Quốc OaiHuyện Sóc SơnThị xã Sơn TâyQuận Tây HồHuyện Thạch ThấtHuyện Thanh OaiHuyện Thanh TrìQuận Thanh XuânHuyện Thường TínHuyện Ứng HòaHuyện Đan PhượngHuyện Đông AnhQuận Đống Đa')]</value>
      <webElementGuid>f2170b07-79b0-4d64-b79b-f19d1049127b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
