<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Checkbox_rules</name>
   <tag></tag>
   <elementGuidId>ca2196df-bc18-4d3d-87ed-a99e18687a23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#agreement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='agreement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tôi đã đọc và đồng ý với điều khoản dịch vụ và chính sách bảo mật của ThinkPro.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5006e8a5-1312-48a5-9bc5-6da8a120fe09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>3eca9224-93dc-4c62-9065-7da66994de6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>824732c8-e490-40dc-850b-492122f5847b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>agreement</value>
      <webElementGuid>08672fa3-8ce4-4f29-a88d-ce1717ef5bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agreement&quot;)</value>
      <webElementGuid>223c10c4-1d97-4453-8f79-eb331558432a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='agreement']</value>
      <webElementGuid>2a54b74b-8b4f-43da-b5dd-17f685aca5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkout-form']/div/div[2]/div/div[2]/div[4]/input</value>
      <webElementGuid>0fc7e8c8-a447-45ac-a0be-5859fb8267cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>b7c780e6-48ca-418d-8b04-ac5769304729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'agreement']</value>
      <webElementGuid>671d3427-f4b6-4e52-8c24-c24afd8ee733</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
