<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- district</name>
   <tag></tag>
   <elementGuidId>157c9068-55e3-45f5-acc3-1e3d858607ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='quan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#quan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#quan</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f6dfad55-b525-4118-9b6f-ee66a92f9e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>843394ba-feeb-4972-ad99-fe126034cb2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quan</value>
      <webElementGuid>60fb1ce8-726d-4511-89b5-38e67b641785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>district</value>
      <webElementGuid>f69e95cc-be1b-4a5e-afc3-de6b0e82640c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Chọn Quận/Huyện --Huyện Ba VìQuận Ba ĐìnhQuận Bắc Từ LiêmQuận Cầu GiấyHuyện Chương MỹHuyện Gia LâmQuận Hà ĐôngQuận Hai Bà TrưngHuyện Hoài ĐứcQuận Hoàn KiếmQuận Hoàng MaiQuận Long BiênHuyện Mê LinhHuyện Mỹ ĐứcQuận Nam Từ LiêmHuyện Phú XuyênHuyện Phúc ThọHuyện Quốc OaiHuyện Sóc SơnThị xã Sơn TâyQuận Tây HồHuyện Thạch ThấtHuyện Thanh OaiHuyện Thanh TrìQuận Thanh XuânHuyện Thường TínHuyện Ứng HòaHuyện Đan PhượngHuyện Đông AnhQuận Đống Đa</value>
      <webElementGuid>f7315ac4-d32e-4b98-801c-ff80a8921e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quan&quot;)</value>
      <webElementGuid>5f8daac8-97b1-4d74-aa86-f205c09952f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='quan']</value>
      <webElementGuid>52592c27-98f4-403e-8bc5-e49ec3689903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkout-form']/div/div/div/div[2]/div[3]/div[2]/select</value>
      <webElementGuid>d3f82163-013b-4c8c-a311-745f06faa91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>6322d2ec-7589-42b3-8d92-401fd96cf258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::select[1]</value>
      <webElementGuid>8f574ed7-aaa2-4340-9d0f-a4d7caf8dc4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>6c43ddd0-3792-47b0-b8cb-7d1c42f98458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'quan' and @name = 'district' and (text() = '-- Chọn Quận/Huyện --Huyện Ba VìQuận Ba ĐìnhQuận Bắc Từ LiêmQuận Cầu GiấyHuyện Chương MỹHuyện Gia LâmQuận Hà ĐôngQuận Hai Bà TrưngHuyện Hoài ĐứcQuận Hoàn KiếmQuận Hoàng MaiQuận Long BiênHuyện Mê LinhHuyện Mỹ ĐứcQuận Nam Từ LiêmHuyện Phú XuyênHuyện Phúc ThọHuyện Quốc OaiHuyện Sóc SơnThị xã Sơn TâyQuận Tây HồHuyện Thạch ThấtHuyện Thanh OaiHuyện Thanh TrìQuận Thanh XuânHuyện Thường TínHuyện Ứng HòaHuyện Đan PhượngHuyện Đông AnhQuận Đống Đa' or . = '-- Chọn Quận/Huyện --Huyện Ba VìQuận Ba ĐìnhQuận Bắc Từ LiêmQuận Cầu GiấyHuyện Chương MỹHuyện Gia LâmQuận Hà ĐôngQuận Hai Bà TrưngHuyện Hoài ĐứcQuận Hoàn KiếmQuận Hoàng MaiQuận Long BiênHuyện Mê LinhHuyện Mỹ ĐứcQuận Nam Từ LiêmHuyện Phú XuyênHuyện Phúc ThọHuyện Quốc OaiHuyện Sóc SơnThị xã Sơn TâyQuận Tây HồHuyện Thạch ThấtHuyện Thanh OaiHuyện Thanh TrìQuận Thanh XuânHuyện Thường TínHuyện Ứng HòaHuyện Đan PhượngHuyện Đông AnhQuận Đống Đa')]</value>
      <webElementGuid>a41edd18-931a-4874-9088-776f93947071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quận/Huyện'])[1]/following::select[1]</value>
      <webElementGuid>aa69160e-bc7d-4f18-9e82-678ed1d349c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tỉnh/Thành phố'])[1]/following::select[2]</value>
      <webElementGuid>700fc87c-5c65-4eb0-b2f7-22a1aceb90b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phường/Xã'])[1]/preceding::select[1]</value>
      <webElementGuid>ce57d6a8-93a9-4ff5-8e66-7084ff73bd5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Địa chỉ chi tiết'])[1]/preceding::select[2]</value>
      <webElementGuid>d3438643-2171-47e1-85c0-65defbd8d738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'quan' and @name = 'district' and (text() = '-- Chọn Quận/Huyện --Huyện Bình LụcThị xã Duy TiênHuyện Kim BảngHuyện Lý NhânThành phố Phủ LýHuyện Thanh Liêm' or . = '-- Chọn Quận/Huyện --Huyện Bình LụcThị xã Duy TiênHuyện Kim BảngHuyện Lý NhânThành phố Phủ LýHuyện Thanh Liêm')]</value>
      <webElementGuid>e9637435-632e-44c9-aa9c-794eead7c3dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
