<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- ward</name>
   <tag></tag>
   <elementGuidId>d57bd9ef-8db6-4b30-acdd-2a43ef1f6979</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='phuong']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phuong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#phuong</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>60bce706-9944-44f6-89c9-bc546edea916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>0b62fc03-faac-4393-b3b9-261d7e9837b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phuong</value>
      <webElementGuid>290b5a6e-570c-475b-b2f4-174cc9e7e969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ward</value>
      <webElementGuid>f0300f63-2286-4a2a-92d3-b1e43f3797aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Chọn Phường/Xã --Xã Hạ MỗXã Hồng HàXã Liên HàXã Liên HồngXã Liên TrungThị trấn PhùngXã Phương ĐìnhXã Song PhượngXã Tân HộiXã Tân LậpXã Thọ AnXã Thọ XuânXã Thượng MỗXã Trung ChâuXã Đan PhượngXã Đồng Tháp</value>
      <webElementGuid>b311503b-3fd2-4091-8026-cf48051f493b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phuong&quot;)</value>
      <webElementGuid>8c879adc-a287-4d9c-b768-99ff3880ceac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='phuong']</value>
      <webElementGuid>7af8089e-af89-4456-ac64-e97449ac066a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkout-form']/div/div/div/div[2]/div[3]/div[3]/select</value>
      <webElementGuid>9846cb18-610d-43c2-8ff7-5e5255ae5748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[1]</value>
      <webElementGuid>4759f189-2692-4b6e-845a-6104bd5cb8e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::select[1]</value>
      <webElementGuid>d0a9e0b9-093d-4af0-b4b5-8befb66c7ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>10f056f1-38d0-4ec3-b5d2-bc04133a925d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'phuong' and @name = 'ward' and (text() = '-- Chọn Phường/Xã --Xã Hạ MỗXã Hồng HàXã Liên HàXã Liên HồngXã Liên TrungThị trấn PhùngXã Phương ĐìnhXã Song PhượngXã Tân HộiXã Tân LậpXã Thọ AnXã Thọ XuânXã Thượng MỗXã Trung ChâuXã Đan PhượngXã Đồng Tháp' or . = '-- Chọn Phường/Xã --Xã Hạ MỗXã Hồng HàXã Liên HàXã Liên HồngXã Liên TrungThị trấn PhùngXã Phương ĐìnhXã Song PhượngXã Tân HộiXã Tân LậpXã Thọ AnXã Thọ XuânXã Thượng MỗXã Trung ChâuXã Đan PhượngXã Đồng Tháp')]</value>
      <webElementGuid>fb97e7ab-5c03-4cee-9546-9013ea05cf10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phường/Xã'])[1]/following::select[1]</value>
      <webElementGuid>b3943172-1f6f-4e03-b8cf-3b3e8692d369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quận/Huyện'])[1]/following::select[2]</value>
      <webElementGuid>662b54b6-d695-4a9b-a353-3cde03f8adec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Địa chỉ chi tiết'])[1]/preceding::select[1]</value>
      <webElementGuid>cf8158f8-7587-481d-a31c-3696a43a192d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cập nhật thông tin'])[1]/preceding::select[1]</value>
      <webElementGuid>a2949cac-2539-45fd-a148-12fbdff8bee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'phuong' and @name = 'ward' and (text() = '-- Chọn Phường/Xã --Thị trấn Kiện KhêXã Liêm CầnXã Liêm PhongXã Liêm SơnXã Liêm ThuậnXã Liêm TúcThị trấn Tân ThanhXã Thanh HàXã Thanh HảiXã Thanh HươngXã Thanh NghịXã Thanh NguyênXã Thanh PhongXã Thanh TâmXã Thanh TânXã Thanh Thủy' or . = '-- Chọn Phường/Xã --Thị trấn Kiện KhêXã Liêm CầnXã Liêm PhongXã Liêm SơnXã Liêm ThuậnXã Liêm TúcThị trấn Tân ThanhXã Thanh HàXã Thanh HảiXã Thanh HươngXã Thanh NghịXã Thanh NguyênXã Thanh PhongXã Thanh TâmXã Thanh TânXã Thanh Thủy')]</value>
      <webElementGuid>915c8736-e4ef-4981-a8f8-ea9b11a102d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
