<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_delete_voucher</name>
   <tag></tag>
   <elementGuidId>e5c140ad-1f70-4c26-850c-429a9c37b143</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-danger.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;DONHANG500TRIEU Áp dụng với các đơn hàng có giá > 500 triệu Phần trăm 70% 1/5/2025 - 31/5/2025 9 Hết hạn  &quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>599fb1d4-cc89-404f-a913-8f6f9c183e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6842c42a-3764-49b7-918a-7a5343e592a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-sm</value>
      <webElementGuid>f7ee3f9a-8d05-42e8-a632-2942a66edd2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[8]/div[@class=&quot;d-flex&quot;]/form[1]/button[@class=&quot;btn btn-danger btn-sm&quot;]</value>
      <webElementGuid>f6c00f14-9029-4fcb-aeb0-33c508d3ae19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>82f5f4e3-045f-42ed-bcd7-2eee07cdddc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[8]/div/form/button</value>
      <webElementGuid>b6575f32-ee4e-42be-bd7c-3e0e5edf74d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hết hạn'])[1]/following::button[1]</value>
      <webElementGuid>d35c38f2-3734-4a57-823a-8f1609c59368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phần trăm'])[1]/following::button[1]</value>
      <webElementGuid>84085e04-189e-4515-8ff0-06afae7a4dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PDU'])[1]/preceding::button[1]</value>
      <webElementGuid>112fc2cf-9e9e-41ac-b9a5-1c6cc54da260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mã khuyến mãi dành cho sinh viên trường Đại Học Phương Đông'])[1]/preceding::button[1]</value>
      <webElementGuid>ebc7dfbc-a0df-484c-82a6-0371cd41b286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>e4a83283-017e-4606-8dcb-24f93476890e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit']</value>
      <webElementGuid>667e8b64-93e8-44d5-a9e2-ffded50678af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
