<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- district</name>
   <tag></tag>
   <elementGuidId>adfb4c95-502d-4e5c-9176-7e53c39eda6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#quan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='quan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#quan</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b1026c18-1ab1-4990-b187-3817dbc1f5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>36ae58c5-bb05-4b34-9804-0159ad64a654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quan</value>
      <webElementGuid>9a7b7dc3-77e8-417c-9273-125a10718127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>district</value>
      <webElementGuid>084c01e1-a4f5-4c5f-8ce4-8dbd6f4d7cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Chọn Quận/Huyện --Huyện Bình LụcThị xã Duy TiênHuyện Kim BảngHuyện Lý NhânThành phố Phủ LýHuyện Thanh Liêm</value>
      <webElementGuid>15414e62-bc6e-4659-94dd-27d0eaaf1841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quan&quot;)</value>
      <webElementGuid>3978419a-742c-4248-a5d3-d6918825d342</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='quan']</value>
      <webElementGuid>5c30fc1a-e51a-4d36-b0bc-0940787bdf79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div[3]/div[2]/div/div/div/div/div/form/div[4]/div[2]/select</value>
      <webElementGuid>8ccb5e7e-1f68-4300-88dc-53880b49b44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::select[1]</value>
      <webElementGuid>b1c74b5a-f261-467b-ab94-6a9dee138ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/preceding::select[1]</value>
      <webElementGuid>0c5d14f0-c391-4705-b786-104bb8f6293d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/select</value>
      <webElementGuid>10a03703-992e-45ce-a023-b7b33c369755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'quan' and @name = 'district' and (text() = '-- Chọn Quận/Huyện --Huyện Bình LụcThị xã Duy TiênHuyện Kim BảngHuyện Lý NhânThành phố Phủ LýHuyện Thanh Liêm' or . = '-- Chọn Quận/Huyện --Huyện Bình LụcThị xã Duy TiênHuyện Kim BảngHuyện Lý NhânThành phố Phủ LýHuyện Thanh Liêm')]</value>
      <webElementGuid>17f30b41-7b22-4789-adf8-6f5fbb89083a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
