<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- ward</name>
   <tag></tag>
   <elementGuidId>27cd53da-e4e0-4194-914a-660a172969e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phuong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='phuong']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#phuong</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f623edf3-3eed-4bb7-a95d-f8ecf80f5add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ada04874-785f-46e7-9ebe-ee674e32b70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phuong</value>
      <webElementGuid>20d662a2-753a-456d-a5a4-7a838f607df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ward</value>
      <webElementGuid>47afe92b-9bc5-4472-a1d3-e81f84454406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Chọn Phường/Xã --Phường Bạch ThượngPhường Châu GiangXã Chuyên NgoạiPhường Duy HảiPhường Duy MinhPhường Hòa MạcPhường Hoàng ĐôngXã Mộc BắcXã Mộc NamXã Tiên NgoạiPhường Tiên NộiXã Tiên SơnXã Trác VănPhường Yên BắcXã Yên NamPhường Đồng Văn</value>
      <webElementGuid>d5b2d703-1199-4c87-bd17-17403220f1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phuong&quot;)</value>
      <webElementGuid>f6308ba9-7468-483a-93b9-c7c0edced97b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='phuong']</value>
      <webElementGuid>c74c07ec-5ad4-4639-9f0c-eccc41b72736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div[3]/div[2]/div/div/div/div/div/form/div[4]/div[3]/select</value>
      <webElementGuid>cc41a934-a478-4211-9e5f-763d1aba2c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::select[1]</value>
      <webElementGuid>fa8ae96e-ebef-453b-9557-5f0a0e9cfe6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mật khẩu mới (để trống nếu không thay đổi)'])[1]/preceding::select[1]</value>
      <webElementGuid>7d9018b1-0abc-455c-afb6-98343b90039a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mật khẩu phải có ít nhất 6 ký tự'])[1]/preceding::select[1]</value>
      <webElementGuid>7fedb287-05cd-489f-90d4-262a6b6345fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>356a8c41-9903-434a-987b-5fbb9abd79e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'phuong' and @name = 'ward' and (text() = '-- Chọn Phường/Xã --Phường Bạch ThượngPhường Châu GiangXã Chuyên NgoạiPhường Duy HảiPhường Duy MinhPhường Hòa MạcPhường Hoàng ĐôngXã Mộc BắcXã Mộc NamXã Tiên NgoạiPhường Tiên NộiXã Tiên SơnXã Trác VănPhường Yên BắcXã Yên NamPhường Đồng Văn' or . = '-- Chọn Phường/Xã --Phường Bạch ThượngPhường Châu GiangXã Chuyên NgoạiPhường Duy HảiPhường Duy MinhPhường Hòa MạcPhường Hoàng ĐôngXã Mộc BắcXã Mộc NamXã Tiên NgoạiPhường Tiên NộiXã Tiên SơnXã Trác VănPhường Yên BắcXã Yên NamPhường Đồng Văn')]</value>
      <webElementGuid>dfc0cb2d-2300-4a88-b0d3-9b9aa57bb7f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
