<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_view_rating_tab</name>
   <tag></tag>
   <elementGuidId>f03c85d5-8c3f-472a-a0d6-9dc8eb4934bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reviews-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='reviews-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Đánh giá (3)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>86821db8-e68a-4a32-89ba-291fb3acd641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link active</value>
      <webElementGuid>63675c80-ce0f-491a-ae39-8b767ae42e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reviews-tab</value>
      <webElementGuid>19446fe5-b64d-4685-91a5-d1ca3f82669e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>504026ce-bfc4-4adc-8dda-add872b64713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#reviews</value>
      <webElementGuid>c42fabea-7077-4971-930f-91798240b18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>47cd224c-5ee5-4984-a500-7f11201ceecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>e1bb819d-2a81-4ec2-bcd2-1c708e93dcae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>62cc6c11-2abe-4ab8-8ae2-25a9285c03fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đánh giá (3)</value>
      <webElementGuid>fa8d300e-0622-4118-aab4-6e6ca18ed9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reviews-tab&quot;)</value>
      <webElementGuid>3212c2fb-f9ee-4496-94da-3a49a6db5029</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='reviews-tab']</value>
      <webElementGuid>20380c6a-d711-4ada-9637-89782bdfb55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='productTab']/li[3]/button</value>
      <webElementGuid>8df3e34d-3206-446b-a018-2f4e9222fda1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông số kỹ thuật'])[1]/following::button[1]</value>
      <webElementGuid>b2296734-d1b6-4939-af12-35af9a428aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mô tả chi tiết'])[1]/following::button[2]</value>
      <webElementGuid>4965b2c0-d703-421d-8562-712e3e1b6307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dell Inspiron 7445 2 in 1'])[1]/preceding::button[1]</value>
      <webElementGuid>dfd9b750-5aa0-44e4-bd15-71e63da284b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dell Inspiron 7445 2 in 1 sở hữu ngoại hình sang trọng, nổi bật với khả năng xoay gập 360 độ'])[1]/preceding::button[1]</value>
      <webElementGuid>aa6e81ae-bd0b-40bc-b882-ce10591dc30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đánh giá (3)']/parent::*</value>
      <webElementGuid>9f9d42c6-0583-4ad4-b295-b25129f42332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/button</value>
      <webElementGuid>9b4e8a82-9fc3-445a-bbdf-975cec126963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'reviews-tab' and @type = 'button' and (text() = 'Đánh giá (3)' or . = 'Đánh giá (3)')]</value>
      <webElementGuid>18889ca0-45c2-4ff2-8d76-1164c38e822c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
