<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_review_comment</name>
   <tag></tag>
   <elementGuidId>e4bf1bf8-7501-4222-8810-30e72613ddc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#review-comment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='review-comment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Chia sẻ trải nghiệm của bạn về sản phẩm này...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>36f51dae-6fcc-4cdd-bce4-63f427079445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6ef69c69-f281-4d74-a134-16a4c78f1064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>review-comment</value>
      <webElementGuid>273943ba-2f13-4814-ad15-b364e0b8e4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>feedd2ff-705d-43fb-a4fa-d95401a52358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Chia sẻ trải nghiệm của bạn về sản phẩm này...</value>
      <webElementGuid>807be328-8e30-4aa8-9d2c-ae5922d05500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>572d34cc-d696-40ec-aa08-ad8355b8049d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;review-comment&quot;)</value>
      <webElementGuid>ad050918-b7b8-41db-b9b1-50710fd5ce33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='review-comment']</value>
      <webElementGuid>62639478-3ca7-42b9-809c-29c6aca20a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='review-form']/div[2]/textarea</value>
      <webElementGuid>1b6f69c0-a4cf-4973-8668-402ea6516704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>56a0e534-2f0a-41b3-a98f-2714e9a53611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'review-comment' and @placeholder = 'Chia sẻ trải nghiệm của bạn về sản phẩm này...']</value>
      <webElementGuid>47ad8b46-d00f-4adf-8ff9-89b088025222</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
