<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_notification_voucher_content</name>
   <tag></tag>
   <elementGuidId>b40e1f4f-c812-4bf9-8703-261504f96345</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#coupon-message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='coupon-message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Mã giảm giá không hợp lệ&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ee89158c-e912-4cbe-bfbd-777e39707b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coupon-message</value>
      <webElementGuid>99a4f0be-5943-44f4-9245-8b335e3ca700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-text text-danger mt-2</value>
      <webElementGuid>3ae215ec-dbf9-4e0b-bedf-14c7b9ef9364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mã giảm giá không hợp lệ</value>
      <webElementGuid>88600411-9d4c-4a52-b987-f869cf7a04da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coupon-message&quot;)</value>
      <webElementGuid>3c240775-c68f-4018-a041-6691dee347dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='coupon-message']</value>
      <webElementGuid>27811d1c-34e4-44cd-8663-551eb1d9491e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='coupon-form']/div[2]</value>
      <webElementGuid>7a476ca3-79c8-4733-b5d3-65a4c608610f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Áp dụng'])[1]/following::div[1]</value>
      <webElementGuid>4fd04aea-02db-4ec7-8dcf-457794e9ef30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng cộng'])[1]/following::div[3]</value>
      <webElementGuid>9cd5ae7f-645a-4555-bc74-9dcfdf3bdfe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiến hành thanh toán'])[1]/preceding::div[1]</value>
      <webElementGuid>81a27005-9e4d-4a3b-84f0-7b8b1bccff60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mã giảm giá không hợp lệ']/parent::*</value>
      <webElementGuid>ebf26731-3ba7-4928-bd34-8eba7f94d641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]</value>
      <webElementGuid>5ad7b23c-961d-46a8-9f62-24a5068dcaaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'coupon-message' and (text() = 'Mã giảm giá không hợp lệ' or . = 'Mã giảm giá không hợp lệ')]</value>
      <webElementGuid>e81b100f-0aa2-4130-986d-1ab68c74b216</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
