<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ma_voucher</name>
   <tag></tag>
   <elementGuidId>e655cfbd-2a1e-49bd-bcfd-5607a1f52b19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#coupon-code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='coupon-code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Mã giảm giá&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>996adcf6-d0a3-4e0e-b69c-cd4078c5635f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f5115969-8a95-48f9-84b4-35c7152e1110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3a89b121-539c-425f-8762-8659af47eebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coupon-code</value>
      <webElementGuid>834136a1-1f0c-4d47-a424-0b9595515891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mã giảm giá</value>
      <webElementGuid>34de8f72-1dd9-462c-af4d-a7d5a4dc3850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coupon-code&quot;)</value>
      <webElementGuid>3b4c8f37-6589-452e-8aa0-ff065d6eb4bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='coupon-code']</value>
      <webElementGuid>b394c496-ce03-4e58-96e8-56c1723ce078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='coupon-form']/div/input</value>
      <webElementGuid>281ca7b1-9fc3-455e-af48-a08d92d1eb2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/form/div/input</value>
      <webElementGuid>c166322a-13fd-4b67-bd95-a77bd8e171c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'coupon-code' and @placeholder = 'Mã giảm giá']</value>
      <webElementGuid>7e013c26-2238-4a18-901b-db91aed58778</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
