<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- ward</name>
   <tag></tag>
   <elementGuidId>546c1d5e-2a15-4e05-8d09-c328a7f6e77b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='phuong']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phuong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Phường/Xã&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7d2562d8-f9a2-415b-b75a-a85fd0fc7870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>660532f9-71c1-4e7e-9749-bedffa0dbd4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phuong</value>
      <webElementGuid>c4c393fd-7799-4b3c-851b-21b567594dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ward</value>
      <webElementGuid>be9410f9-d85d-4f20-8375-fd37485ac7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Chọn Phường/Xã --Thị trấn Kiện KhêXã Liêm CầnXã Liêm PhongXã Liêm SơnXã Liêm ThuậnXã Liêm TúcThị trấn Tân ThanhXã Thanh HàXã Thanh HảiXã Thanh HươngXã Thanh NghịXã Thanh NguyênXã Thanh PhongXã Thanh TâmXã Thanh TânXã Thanh Thủy</value>
      <webElementGuid>dbe44c3d-7cff-4aef-a056-169eef5722b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phuong&quot;)</value>
      <webElementGuid>879429d4-a49c-41b2-a422-cf198bc07792</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='phuong']</value>
      <webElementGuid>4862f378-01cb-48f2-93d1-7e2b729a7f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phường/Xã'])[1]/following::select[1]</value>
      <webElementGuid>383d6b67-db39-48f4-a13c-ce279fbae9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quận/Huyện'])[1]/following::select[2]</value>
      <webElementGuid>16f76d08-c0fe-4c0c-bb87-a8c9626efe0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Địa chỉ chi tiết'])[1]/preceding::select[1]</value>
      <webElementGuid>76523bfb-e122-4cc5-aeab-80bf08469245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cập nhật thông tin'])[1]/preceding::select[1]</value>
      <webElementGuid>959be2c3-0b36-42d8-a376-acbc44f09eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>95388ac9-c306-4ffe-8d6e-8d11644f40b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'phuong' and @name = 'ward' and (text() = '-- Chọn Phường/Xã --Thị trấn Kiện KhêXã Liêm CầnXã Liêm PhongXã Liêm SơnXã Liêm ThuậnXã Liêm TúcThị trấn Tân ThanhXã Thanh HàXã Thanh HảiXã Thanh HươngXã Thanh NghịXã Thanh NguyênXã Thanh PhongXã Thanh TâmXã Thanh TânXã Thanh Thủy' or . = '-- Chọn Phường/Xã --Thị trấn Kiện KhêXã Liêm CầnXã Liêm PhongXã Liêm SơnXã Liêm ThuậnXã Liêm TúcThị trấn Tân ThanhXã Thanh HàXã Thanh HảiXã Thanh HươngXã Thanh NghịXã Thanh NguyênXã Thanh PhongXã Thanh TâmXã Thanh TânXã Thanh Thủy')]</value>
      <webElementGuid>9352adc0-bfa5-449d-8ba4-86c2fcc6f32b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
