<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Chn QunHuyn</name>
   <tag></tag>
   <elementGuidId>7d7804bc-3e45-423e-8ebf-0a08c9106582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='quan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#quan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Quận/Huyện&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>257dc4df-f35e-49f5-8910-6164bc511a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a2a97b08-7af6-4290-9fef-96b470e762a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quan</value>
      <webElementGuid>432aa24e-19ae-4516-9829-8c386a3f6ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>district</value>
      <webElementGuid>3afe969c-baab-4bb6-946c-4957992a0ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Chọn Quận/Huyện --Huyện Bình LụcThị xã Duy TiênHuyện Kim BảngHuyện Lý NhânThành phố Phủ LýHuyện Thanh Liêm</value>
      <webElementGuid>939c8f8e-ff01-4587-b380-700076aec546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quan&quot;)</value>
      <webElementGuid>7d28b001-13cb-4307-a45c-5e89349bdfc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='quan']</value>
      <webElementGuid>51d3dfca-da51-4b55-a93e-33e479e685b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quận/Huyện'])[1]/following::select[1]</value>
      <webElementGuid>ca4b7283-c0cf-4f3b-b714-9de61c8e155a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tỉnh/Thành phố'])[1]/following::select[2]</value>
      <webElementGuid>ae1091a4-a6f4-491b-a063-e781a14d9e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phường/Xã'])[1]/preceding::select[1]</value>
      <webElementGuid>2a9fe32c-bda7-4b73-9743-4f67958a1b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Địa chỉ chi tiết'])[1]/preceding::select[2]</value>
      <webElementGuid>587399df-48ba-4a34-b6d5-e0a7c2289ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>6b7fe77a-7751-4f49-957f-ea9cb4293e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'quan' and @name = 'district' and (text() = '-- Chọn Quận/Huyện --Huyện Bình LụcThị xã Duy TiênHuyện Kim BảngHuyện Lý NhânThành phố Phủ LýHuyện Thanh Liêm' or . = '-- Chọn Quận/Huyện --Huyện Bình LụcThị xã Duy TiênHuyện Kim BảngHuyện Lý NhânThành phố Phủ LýHuyện Thanh Liêm')]</value>
      <webElementGuid>6d80bccc-10c9-4ef7-b94e-8aecdb2252ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
