<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- ward</name>
   <tag></tag>
   <elementGuidId>294d75cb-7c6f-460e-b453-1e1a77fb4780</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='phuong']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phuong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#phuong</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>954b6bc7-3277-495e-8e0f-61638d9fed4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>81aab56e-07f5-43a7-bcbb-5e0294149439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phuong</value>
      <webElementGuid>4c327de9-8c59-408c-9ff7-c76097ce4fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ward</value>
      <webElementGuid>b332bbc3-01c9-42bd-9b18-7bbcbd34a9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Chọn Phường/Xã --Xã Hạ MỗXã Hồng HàXã Liên HàXã Liên HồngXã Liên TrungThị trấn PhùngXã Phương ĐìnhXã Song PhượngXã Tân HộiXã Tân LậpXã Thọ AnXã Thọ XuânXã Thượng MỗXã Trung ChâuXã Đan PhượngXã Đồng Tháp</value>
      <webElementGuid>24c4097b-b506-4b6f-a083-9ac3f71ed454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phuong&quot;)</value>
      <webElementGuid>882e179c-bd6f-42e2-8213-59038d8d0f2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='phuong']</value>
      <webElementGuid>209198fd-570c-49a9-98fc-abd20d3e6e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div[3]/div[2]/div/div/div/div/div/form/div[4]/div[3]/select</value>
      <webElementGuid>ba076b0f-d674-442e-98f8-7a0121045597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::select[1]</value>
      <webElementGuid>97b494c0-aa18-4aea-9dfc-36e0a253b896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/preceding::select[1]</value>
      <webElementGuid>68723d65-d4c1-45cc-9b75-79634b15ee3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>c108c60f-fa58-4ea9-8546-f074eae3508f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'phuong' and @name = 'ward' and (text() = '-- Chọn Phường/Xã --Xã Hạ MỗXã Hồng HàXã Liên HàXã Liên HồngXã Liên TrungThị trấn PhùngXã Phương ĐìnhXã Song PhượngXã Tân HộiXã Tân LậpXã Thọ AnXã Thọ XuânXã Thượng MỗXã Trung ChâuXã Đan PhượngXã Đồng Tháp' or . = '-- Chọn Phường/Xã --Xã Hạ MỗXã Hồng HàXã Liên HàXã Liên HồngXã Liên TrungThị trấn PhùngXã Phương ĐìnhXã Song PhượngXã Tân HộiXã Tân LậpXã Thọ AnXã Thọ XuânXã Thượng MỗXã Trung ChâuXã Đan PhượngXã Đồng Tháp')]</value>
      <webElementGuid>0b0abb06-4eda-48a1-a151-ccc4ea317d32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
