<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- district</name>
   <tag></tag>
   <elementGuidId>1e22db5f-d9c3-4c8b-bad1-a5a7fe737c66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='quan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#quan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#quan</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cddf8886-d129-4afe-9eff-f56d5a89f02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>744c7447-a185-4733-9d84-9d92c86533b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quan</value>
      <webElementGuid>30e1acba-2139-48d7-a366-549eca377c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>district</value>
      <webElementGuid>4c2daf53-31d9-41fe-ba7a-0876f33d1dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Chọn Quận/Huyện --Huyện Ba VìQuận Ba ĐìnhQuận Bắc Từ LiêmQuận Cầu GiấyHuyện Chương MỹHuyện Gia LâmQuận Hà ĐôngQuận Hai Bà TrưngHuyện Hoài ĐứcQuận Hoàn KiếmQuận Hoàng MaiQuận Long BiênHuyện Mê LinhHuyện Mỹ ĐứcQuận Nam Từ LiêmHuyện Phú XuyênHuyện Phúc ThọHuyện Quốc OaiHuyện Sóc SơnThị xã Sơn TâyQuận Tây HồHuyện Thạch ThấtHuyện Thanh OaiHuyện Thanh TrìQuận Thanh XuânHuyện Thường TínHuyện Ứng HòaHuyện Đan PhượngHuyện Đông AnhQuận Đống Đa</value>
      <webElementGuid>03837209-00ed-4535-90f2-9810b44a09b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quan&quot;)</value>
      <webElementGuid>ba63627c-2ea7-4e3a-aa1d-0ac570aca874</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='quan']</value>
      <webElementGuid>4c2806f2-5789-4873-8cd3-d4504f67bcc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div[3]/div[2]/div/div/div/div/div/form/div[4]/div[2]/select</value>
      <webElementGuid>719bd872-7d6b-4f3d-af88-7333488b2f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::select[1]</value>
      <webElementGuid>b40534d5-0e6d-4d43-bf59-fc79d3b3d04c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/preceding::select[1]</value>
      <webElementGuid>b2b9cd38-1ca7-46f0-814e-800c3196f648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/select</value>
      <webElementGuid>a07febdc-ef73-48d1-8641-816cdd87c6db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'quan' and @name = 'district' and (text() = '-- Chọn Quận/Huyện --Huyện Ba VìQuận Ba ĐìnhQuận Bắc Từ LiêmQuận Cầu GiấyHuyện Chương MỹHuyện Gia LâmQuận Hà ĐôngQuận Hai Bà TrưngHuyện Hoài ĐứcQuận Hoàn KiếmQuận Hoàng MaiQuận Long BiênHuyện Mê LinhHuyện Mỹ ĐứcQuận Nam Từ LiêmHuyện Phú XuyênHuyện Phúc ThọHuyện Quốc OaiHuyện Sóc SơnThị xã Sơn TâyQuận Tây HồHuyện Thạch ThấtHuyện Thanh OaiHuyện Thanh TrìQuận Thanh XuânHuyện Thường TínHuyện Ứng HòaHuyện Đan PhượngHuyện Đông AnhQuận Đống Đa' or . = '-- Chọn Quận/Huyện --Huyện Ba VìQuận Ba ĐìnhQuận Bắc Từ LiêmQuận Cầu GiấyHuyện Chương MỹHuyện Gia LâmQuận Hà ĐôngQuận Hai Bà TrưngHuyện Hoài ĐứcQuận Hoàn KiếmQuận Hoàng MaiQuận Long BiênHuyện Mê LinhHuyện Mỹ ĐứcQuận Nam Từ LiêmHuyện Phú XuyênHuyện Phúc ThọHuyện Quốc OaiHuyện Sóc SơnThị xã Sơn TâyQuận Tây HồHuyện Thạch ThấtHuyện Thanh OaiHuyện Thanh TrìQuận Thanh XuânHuyện Thường TínHuyện Ứng HòaHuyện Đan PhượngHuyện Đông AnhQuận Đống Đa')]</value>
      <webElementGuid>4e5ac741-142b-469c-9bda-9eb5d75bb3ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
