<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_notification_when_add_product_to_cart</name>
   <tag></tag>
   <elementGuidId>6e18117e-f697-4fa5-a2f1-d54968fa5474</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toastMessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toastMessage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Đã thêm sản phẩm vào giỏ hàng&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dc400815-cbfb-4424-b320-136b766cfda0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toastMessage</value>
      <webElementGuid>0351ed59-1fc1-43ce-bc4f-7859007a89e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đã thêm sản phẩm vào giỏ hàng</value>
      <webElementGuid>527e35d5-cfdf-4a23-bea1-1974cca2b27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toastMessage&quot;)</value>
      <webElementGuid>2b03b47e-b067-494d-8e96-0c2ee1bb6fed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='toastMessage']</value>
      <webElementGuid>ba526b9f-ccec-4e4a-80be-6a9ef5cf41ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-toast']/div/div/div[2]</value>
      <webElementGuid>3ca18ac8-ccf5-412c-b2f8-9c6958970002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thành công'])[1]/following::div[1]</value>
      <webElementGuid>8850fce8-9c89-48c4-b2fd-185985929ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laptop'])[1]/following::div[6]</value>
      <webElementGuid>272ba549-0aa3-494a-bf2d-9196260ab685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng ký'])[1]/preceding::div[2]</value>
      <webElementGuid>5d07ad19-04cb-4daf-bb52-47d76840ee01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[1]/preceding::div[2]</value>
      <webElementGuid>cd3be346-e2c7-44cb-99f0-aff53f2fd6eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đã thêm sản phẩm vào giỏ hàng']/parent::*</value>
      <webElementGuid>66424818-3439-46dd-99ac-850056d793a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>fcc9ef41-e63b-45ce-9afc-8a740db20ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'toastMessage' and (text() = 'Đã thêm sản phẩm vào giỏ hàng' or . = 'Đã thêm sản phẩm vào giỏ hàng')]</value>
      <webElementGuid>86e92775-1926-479b-836a-2608cf3e657c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
